CREATE TABLE ADDRESS
(
ID INT IDENTITY(1,1),
CUSTOMER_ID INT NOT NULL,
COUNTRY TINYINT NOT NULL,
CITY SMALLINT NOT NULL,
TOWN INT NOT NULL,
DISTRICT INT NOT NULL,
ADDRESS_TEXT VARCHAR(500) NOT NULL,

CONSTRAINT PK_ADDRESS PRIMARY KEY (ID),
CONSTRAINT FK_ADDRESS_CUSTOMERS FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID) ON DELETE CASCADE
)