CREATE TABLE ITEMS
(
ID INT IDENTITY(1,1),
ITEM_CODE VARCHAR(50) NOT NULL,
ITEM_NAME VARCHAR(100) NOT NULL,
UNIT_PRICE FLOAT NOT NULL,
BRAND VARCHAR(50) NOT NULL,
CATEGORY1 VARCHAR(50) NOT NULL,
CATEGORY2 VARCHAR(50) NOT NULL,
CATEGORY3 VARCHAR(50) NOT NULL,

CONSTRAINT PK_ITEMS PRIMARY KEY CLUSTERED (ID ASC)
)